//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Loja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryProduct
    {
        public int idCategoryProduct { get; set; }
        public int idCategory { get; set; }
        public int idProduct { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Product Product { get; set; }
    }
}
