//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Loja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRequest
    {
        public int idItemRequest { get; set; }
        public int amountItemRequest { get; set; }
        public decimal priceItemRequest { get; set; }
        public int idProduct { get; set; }
        public int idRequest { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Request Request { get; set; }
    }
}
