//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Loja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ItemRequest = new HashSet<ItemRequest>();
        }
    
        public int idProduct { get; set; }
        public string nameProduct { get; set; }
        public string descriptionProduct { get; set; }
        public decimal priceProduct { get; set; }
        public Nullable<decimal> discountProduct { get; set; }
        public bool activeProduct { get; set; }
        public int amountProduct { get; set; }
        public int idCategory { get; set; }
        public int idManagement { get; set; }
        public string imageProduct { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRequest> ItemRequest { get; set; }
        public virtual Management Management { get; set; }
    }
}
