//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Loja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.ItemRequest = new HashSet<ItemRequest>();
        }
    
        public int idRequest { get; set; }
        public System.DateTime dataRequest { get; set; }
        public int idClient { get; set; }
        public int idStatusRequest { get; set; }
        public int idPayment { get; set; }
        public int idAddress { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRequest> ItemRequest { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual StatusRequest StatusRequest { get; set; }
    }
}
